apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: desafio-k8s
type: Opaque
stringData:
  POSTGRES_USER: desafio_user
  POSTGRES_PASSWORD: desafio_pass
  DATABASE_URL: postgres://desafio_user:desafio_pass@postgres:5432/desafio_db
