apiVersion: v1
kind: Service
metadata:
  name: postgrest
  namespace: desafio-k8s
  labels:
    app.kubernetes.io/name: postgrest
    app.kubernetes.io/instance: postgrest
    app.kubernetes.io/part-of: k8s-postgrest-challenge
    app.kubernetes.io/managed-by: kubectl
spec:
  selector:
    app: postgrest
  ports:
    - port: 3000
      targetPort: 3000
